export const API_METHODS = {
    LIST_VERSIONS: 'list-versions',
    CREATE_VERSION: 'create-version',
    CURRENT_VERSION: 'current-version',
    FILE_PICKER: 'file-picker',
    RECENT_PROJECTS: 'recent-projects',
    SAVE_PROJECT: 'save-project',
    DELETE_PROJECT: 'delete_project',
    SAVE_TD_PATH: 'save-td-path',
    GET_TD_PATH: 'get-td-path',
    OPEN_TD: 'open-toe',
    CREATE_PROJECT: 'create-project',
    GO_TO_VERSION: 'go-to-version',
    WATCH_PROJECT: 'watch-project',
    UNWATCH_PROJECT: 'unwatch-project',
    GET_TEMPLATES: 'get-templates',
    COMPARE: 'compare-versions',
    GET_STATE: 'get-state',
    PULL: 'pull',
    PUSH: 'push',
    FINISH_MERGE: "finish-merge",
    AUTHENTICATE_USER: 'authenticate-user',
    GET_USER: 'get-user',
    GET_REMOTE_PROJECTS: 'get-remote-projects',
    LOGOUT: 'logout',
}