### try post user
POST http://35.206.108.190:80/api/v1/admin/users
Content-Type: application/json

{
  "username": "BraveJero2",
  "email": "brave2@jero.test",
  "password": "testtest",
  "must_change_password": false
}

### pasos:
### > docker network create gitea-network
### > docker run -d \
### --name giteadb \
### -e POSTGRES_USER=postgres \
### -e POSTGRES_PASSWORD=postgres \
### -e POSTGRES_DB=gitea \
### -p 3333:5432 \
### postgres:14
### > docker network connect gitea-network giteadb
### > docker build -t mariana-gitea .
### > sudo docker run -d --name gitea5 --network gitea-network -p 80:3000   -e DB_TYPE=postgres  -e DB_HOST=giteadb:5432  -e DB_NAME=gitea  -e DB_USER=postgres  -e DB_PASSWD=postgres -v /mnt/disks/gitea-data:/data mariana-gitea
